### ISSUE TITLE
Rethink Button(s)

### ISSUE THREAD

**Issue by subhoney** [subhoney/IM_Chrome#2]
The calculate and refresh buttons are old-school and stale. Rethink their look, feel and position.

At the very least, they should be bigger, and have a more distributed feel on the page.

**Comment by subhoney** [comment]
This issue may be the same as the "rethink columns" issue. I'm going to take this one as well. If it suits you, focus on the disable-before-ready calculate button.

**Comment by ADunigan** [comment]
Good deal.  I've just about got the disable function knocked out, but for the life of me I can't get the button to "gray out" when disabled, no matter what I try.

**Comment by ADunigan** [comment]
Nevermind, got it. Stupid button.
