### ISSUE TITLE
Calculate Button: Disabled Until Ready

### ISSUE THREAD

**Issue by subhoney** [subhoney/IM_Chrome#3]
Use JQuery to disable the "Calculate!" button until all information is filled in. 

Fiddle: http://jsfiddle.net/A7QtF/

**Comment by ADunigan** [comment]
Button disabled until enough items are filled in.  Will leave the issue open until we can verify functionality with the new buttons you are working on.

**Comment by subhoney** [comment]
Bah, push that sucker. I wanna see it.                                 

I won't have a chance to finish the mock before tomorrow  (homework all night tonight). But I'm curious!

**Comment by ADunigan** [comment]
It's working for just a placeholder condition.  Once the columns are eliminated, it'll be crazy simple to implement fully.
